---
- name: Configure SITE1-R1 management interface
  hosts: SITE1-R1
  gather_facts: false
  connection: local

  vars:
    telnet_user: ansible
    telnet_password: ansible123

  tasks:
    - name: Configure management interface
      ansible.netcommon.telnet:
        host: "{{ ansible_host }}"
        port: 23
        user: "{{ telnet_user }}"
        password: "{{ telnet_password }}"
        login_prompt: "Username:"
        password_prompt: "Password:"
        prompts:
          - "[>#]"
        command:
          - terminal length 0
          - configure terminal
          - interface GigabitEthernet0/2
          - description ANSIBLE_MANAGEMENT
          - end
          - write memory
      register: result

    - name: Display configuration result
      ansible.builtin.debug:
        var: result
