---
- name: Test IOL switches through Telnet
  hosts: switches
  gather_facts: false
  connection: local

  vars:
    telnet_user: ansible
    telnet_password: ansible123

  tasks:
    - name: Show interface status
      ansible.netcommon.telnet:
        host: "{{ ansible_host }}"
        port: 23
        user: "{{ telnet_user }}"
        password: "{{ telnet_password }}"
        login_prompt: "Username:"
        password_prompt: "Password:"
        prompts:
          - "[>#]"
        command:
          - terminal length 0
          - show ip interface brief
      register: result

    - name: Display raw result
      ansible.builtin.debug:
        var: result
