plugin: netbox.netbox.nb_inventory

api_endpoint: http://192.168.2.198:8000
validate_certs: false

token: nbt_ym4SNfFofImH.Hi5TWwGn1nHUYUsr252P63prZphMAgrhPuKEXL2A

config_context: false

group_by:
  - region
  - sites  
compose:
  ansible_host: primary_ip4.address | split('/') | first

  ansible_connection: >-
    {{
      'network_cli'
      if device_type.slug in ['cisco-iosv', 'cisco-iol']
      else 'httpapi'
    }}
